name: Build and Deploy Node.js Backend

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Tests (Optional)
        run: npm test || true

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ecommerce-nodejs:latest -f ./Dockerfile .
          docker tag ${{ secrets.DOCKER_USERNAME }}/ecommerce-nodejs:latest ${{ secrets.DOCKER_USERNAME }}/ecommerce-nodejs:${{ github.sha }}

      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/ecommerce-nodejs:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/ecommerce-nodejs:${{ github.sha }}

      - name: Deploy Backend (Simulated)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Deployment process would go here."
          echo "Backend deployed successfully!"
